### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by fickryiman** [zunairkhan811/To-do-list#6]
Your project is awesome, all function is worked well, the suggestion is only one, instead of disable linter line, we suggest to use window.location.reload()

**Comment by zunairkhan811** [comment]
Hi fickry! Thanks for your suggestions. The issue you raised has been fixed now . 😉 

https://github.com/zunairkhan811/To-do-list/blob/dcbad75acd53a0b6658a947e5ec345d63000feae/src/index.js#L17-L24
